version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - $HOME/database/security:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      SERVICE_TAGS: prod
      SERVICE_NAME: postgresdb_security
    networks:
      - security_network

  security_service:
    container_name: security_service_container
    build: .
    image: security_service:v1
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/security
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      SERVICE_TAGS: prod
      SERVICE_NAME: security-service
    depends_on:
      - postgres
    networks:
      - security_network

networks:
  security_network:
    driver: bridge
